### PR TITLE
Fix to support screenshots / images below sub directories

### PR DESCRIPTION
**Pull request by gforcada**
__Big disclaimer:__ code, as seen on the commits is from @datakurre , I'm merely creating the PR on his behalf 😅 

TODO:

- [ ] decide which python and robotframework version ranges we want to support
- [ ] is it compatible with both selenium _and_ playwright based tests?

Part of https://github.com/plone/Products.CMFPlone/issues/3813

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
The Plone coredev buildout 6.0 has been using a checkout of this branch for a long time, and the robot tests seem fine.  So can we get this merged and released please?

I do see that the GitHub-actions in this repo need fixing.  They fail with:

> Action failed with error: Error: Unable to locate executable file: cachix. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

I suppose it is fine to keep this package in the coredev checkouts for a bit longer, and not have a new `robotsuite` version in the upcoming Plone 6.0.7.

**Comment by datakurre** [comment]
I don't remove the branch to not break coredev too soon.

**Comment by datakurre** [comment]
Released robotsuite==2.3.2 

Thanks for the heads up!

**Comment by mauritsvanrees** [comment]
Thanks.  I have updated coredev 6.0 and 6.1 to use the new release, so I will remove this branch.

**Pull request merged**
